//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2S.Brazil2014.Services.BOM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchType
    {
        public MatchType()
        {
            this.Match = new HashSet<Match>();
        }
    
        public int ID { get; set; }
        public string Libelle { get; set; }
    
        public virtual ICollection<Match> Match { get; set; }
    }
}
